'use client';

import React, { useEffect, useState } from 'react';
import { Sparkles, CheckCircle2, AlertCircle, Target } from 'lucide-react';

export default function AIInsights({ agencyId, agencyName }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!agencyId) return;
    let cancelled = false;
    setLoading(true);
    setError('');
    setData(null);

    fetch('/api/insights', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ agencyId }),
    })
      .then(async (res) => {
        const json = await res.json();
        if (!res.ok) throw new Error(json.error || 'Failed to load insights');
        return json;
      })
      .then((json) => { if (!cancelled) setData(json); })
      .catch((err) => { if (!cancelled) setError(err.message); })
      .finally(() => { if (!cancelled) setLoading(false); });

    return () => { cancelled = true; };
  }, [agencyId]);

  if (error) return null; // Stay quiet on the page if AI is misconfigured.

  return (
    <div className="bg-gradient-to-br from-slate-50 to-orange-50/40 border border-orange-100 rounded-lg p-6">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-8 h-8 rounded-lg bg-orange-500/10 flex items-center justify-center">
          <Sparkles className="w-4 h-4 text-orange-500" />
        </div>
        <h2 className="text-lg font-bold text-[#1A2E4A]">AI Insights</h2>
        <span className="text-[10px] font-bold text-orange-600 uppercase tracking-widest bg-orange-100 px-2 py-0.5 rounded-full">
          Beta
        </span>
      </div>

      {loading && (
        <div className="space-y-3">
          <div className="h-3 bg-slate-200 rounded animate-pulse w-3/4" />
          <div className="h-3 bg-slate-200 rounded animate-pulse w-full" />
          <div className="h-3 bg-slate-200 rounded animate-pulse w-2/3" />
          <p className="text-xs text-slate-400 mt-3">Analysing {agencyName}…</p>
        </div>
      )}

      {data && !loading && (
        <div className="space-y-4">
          {data.summary && (
            <p className="text-slate-700 text-sm leading-relaxed">{data.summary}</p>
          )}

          {Array.isArray(data.strengths) && data.strengths.length > 0 && (
            <div>
              <p className="text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-2">Key Strengths</p>
              <div className="flex flex-wrap gap-2">
                {data.strengths.map((s, i) => (
                  <span
                    key={i}
                    className="inline-flex items-center gap-1.5 bg-white border border-slate-200 rounded-full px-3 py-1 text-xs font-medium text-slate-700"
                  >
                    <CheckCircle2 className="w-3 h-3 text-green-500" />
                    {s}
                  </span>
                ))}
              </div>
            </div>
          )}

          {data.best_for && (
            <div className="flex items-start gap-2.5 bg-white border border-slate-100 rounded-lg p-3">
              <Target className="w-4 h-4 text-orange-500 flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-0.5">Best For</p>
                <p className="text-sm text-slate-700 leading-relaxed">{data.best_for}</p>
              </div>
            </div>
          )}

          {data.considerations && (
            <div className="flex items-start gap-2.5 bg-white border border-slate-100 rounded-lg p-3">
              <AlertCircle className="w-4 h-4 text-amber-500 flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-0.5">Worth Asking About</p>
                <p className="text-sm text-slate-700 leading-relaxed">{data.considerations}</p>
              </div>
            </div>
          )}

          <p className="text-[10px] text-slate-400 italic pt-1">
            Generated by AI from public listing data — verify directly with the company.
          </p>
        </div>
      )}
    </div>
  );
}
